# Generated by Django 4.0.4 on 2022-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvs')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='probability',
        ),
    ]
