# Generated by Django 4.0.4 on 2022-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csv_remove_variant_probability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV',
        ),
    ]
